### ISSUE TITLE
How to add end stream function ??

### ISSUE THREAD

**Issue by vickymessii** [ScaleDrone/webrtc#5]
everything is working great i want to add a function for end stream if user one is end stream it should be disconnect from both side.

**Comment by herkyl** [comment]
You can stop the stream like so:
```js
stream.getTracks().forEach(track => track.stop());
```
[Read more..](https://stackoverflow.com/questions/34966809/stop-kill-webrtc-media-stream)

To detect when a user leaves you can use the `member_leave` event from Scaledrone:
```js
room.on('member_leave', member => {
  // Member object
});
```
[Read more..](https://www.scaledrone.com/docs/api-clients/observable-rooms#member-leave-event)

**Comment by vickymessii** [comment]
Thank you so much, Its working.

**Comment by herkyl** [comment]
@vickygillsf glad you got it working
